### ISSUE TITLE
Can't call method "fulltext" on an undefined value

### ISSUE THREAD

**Issue by chorny** [Leont/App-ModuleBuildTiny#29] opened 2016-10-09 15:12 UTC
I'm running `mbtiny dist` on https://github.com/monsieurp/Gentoo-App-Pram.git and receive error:

```
Changes appears to be empty
Can't call method "fulltext" on an undefined value at C:/strawberry514/perl/site/lib/App/ModuleBuildTiny.pm line 51.
```

**Comment by Leont** [comment] 2016-10-11 08:58
This shouldn't happen, and somehow I can't reproduce this easily though I can see how it could happen. Does 16bf190d fix this for you?

**Comment by chorny** [comment] 2016-10-11 09:25
> Does 16bf190 fix this for you?

yes, it does

**Comment by Leont** [comment] 2016-10-12 07:02
> yes, it does

Released as 0.017

**Closed as completed by Leont** 2016-10-12 07:02 UTC

**Comment by monsieurp** [comment] 2016-11-17 08:32
What a coincidence! I ran into the same error a couple of minutes, looked up the error and found this bug report mentioning my own package ;) I just released a new version of Gentoo-App-Pram thanks to your fix! Many thanks @Leont!
